{
    'name': 'QMS Purchase Order',
    'version': '1.0',
    'category': '',
    'sequence': 75,
    'summary': 'Purchase Order',
    'description': "",
    'depends': ['base','purchase'],
    'data': [
            # "data/mail_template_data.xml",
            'security/security_view.xml',
            'security/ir.model.access.csv',
            'wizard/send_approval_wiz.xml',
            'views/purchase_order_view.xml',
            'views/send_approval_po_mail_template.xml',
            # 'views/approved_packaging_mail.xml',
            # 'views/rejected_packaging_mail_template.xml',
            'views/stock_picking_view.xml',
            # 'report/purchase_order_report.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}