{
    'name': 'QMS Sale Order',
    'version': '1.0',
    'category': '',
    'sequence': 75,
    'depends': ['base', 'sale_management', 'sale_stock', 'qms_contact', 'account',
                'product', 'stock_picking_batch', 'mrp','location_wise_quantity', 'purchase_requisition'],
    'data': [
        'security/security_view.xml',
        'security/ir.model.access.csv',
        # 'views/mark_old_mail_template.xml',
        'views/product_view.xml',
        # 'views/send_mo_fo_packing_mail_temp.xml',
        # 'views/send_approval_so_mail_temp.xml',
        # 'views/approved_so_mail_template.xml',
        # 'views/reject_so_mail_template.xml',
        'views/res_company_view.xml',
        'wizard/design_send_view.xml', # remove functionlaity of wizard
        # 'wizard/sample_report_wizard_view.xml',
        # 'wizard/xlsx_output_view.xml',
        # 'wizard/send_mo_pack_view.xml',
        'wizard/approval_send_view.xml',
        # 'wizard/import_gcrm_views.xml',
        # # 'wizard/gcrm_confirm_view.xml',
        'wizard/reject_reason_view.xml',
        'wizard/convert_gift_view.xml',
        # 'wizard/sale_order_approval_view.xml',
        # # 'wizard/so_rejection_view.xml',
        'wizard/gift_rejection_view.xml',
        'wizard/display_products_view.xml',
        'wizard/display_product_stock_view.xml',
        'wizard/sample_approval_view.xml',
        'wizard/sample_reject_view.xml',
        # 'wizard/old_order_warning_view.xml',
        'views/sample_gift_sequence.xml',
        'views/sale_order_views.xml',
        'views/gift_form_view.xml',
        'views/sale_order_line_view.xml',
        'views/default_packaging_config_view.xml',
        'views/package_design_view.xml',
        # 'views/send_for_design_mail_template.xml',
        # 'views/notify_saleperson_mail_template.xml',
        # 'views/convert_to_gift_mail_template.xml',
        # 'views/send_mail_purchase.xml',
        # 'views/display_order_view.xml',
        # 'views/address_report.xml',
        # # 'views/reject_gift_convert_mail_template.xml',
        # 'views/invoice_order_report.xml',
        # 'views/send_for_convert_into_gift.xml',
        # 'views/purchase_requisition_view.xml',
        'views/sale_menus.xml',
        'views/res_users_view.xml',
        # 'views/packaging_views.xml',
        # 'views/customization_email_template.xml',
        # 'views/sample_approval_emails.xml',
        # 'report/order_report.xml',
        # 'report/sample_order_report.xml',
        # 'report/gift_order_report.xml',
        # 'report/report_view.xml',
        # 'report/sale_kit_report.xml',
        'report/pro_forma_invoice_report.xml',
        # 'views/account_invoice_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}