{
    'name': 'QMS Stock Picking',
    'version': '1.0',
    'category': '',
    'sequence': 75,
    'summary': 'Stock Picking',
    'description': "",
    'depends': ['sale_management','stock','base','product'],
    'data': [
        # 'data/email_template_delivery.xml'
        # 'data/sample_gift_picking_data_view.xml',
        # 'data/procurement_rules_data.xml',
        # 'data/email_template_delivery.xml',
        'views/stock_backorder_form.xml',
        'views/delivery_mail_template.xml',
        'views/backorder_mail_template.xml',
        'views/send_intimation_mail_template.xml',
        # 'views/delivery_slips_templater.xml',
        'views/stock_picking_view.xml',
        'views/signed_copy_mail_template.xml',
        'views/stock_move_line_view.xml',
        'views/stock_production_lot_view.xml',
        'views/stock_picking_deshboard.xml',
        # 'views/picking_operation_report.xml',
        'views/stock_warehouse.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}